"""Offline collection and verification of M0/M1 acceptance evidence."""

from ._io import semantic_sha256
from .collector import (
    ACCEPTANCE_TEST_COMMAND,
    AcceptanceEvidenceError,
    CollectionInput,
    CollectionResult,
    collect_acceptance_evidence,
    collect_from_json_file,
)
from .reality import (
    RealityAdapterComponent,
    RealityAdapterLock,
    RealityArtifactRole,
    RealityBundleVerificationResult,
    RealityChainBinding,
    RealityControlDelta,
    RealityDeltaChange,
    RealityEvidenceFact,
    RealityEvidenceIndex,
    RealityEvidenceItem,
    RealityEvidenceManifestV2,
    RealityManifestEntry,
    RealityScopeArtifact,
    RealityTargetLock,
    verify_reality_pre_receipt_bundle,
)
from .semantic_trace import (
    RealityTraceArtifact,
    RealityTraceArtifactV2,
    RealityTraceEvent,
    RealityTraceEventKind,
    RealityTraceEventType,
    RealityTraceEventV2,
    RealityTraceFact,
    RealityTraceLane,
    derive_reality_trace_v2,
)
from .verify import ExpectedProvenance, VerificationResult, verify_acceptance_evidence

__all__ = [
    "ACCEPTANCE_TEST_COMMAND",
    "AcceptanceEvidenceError",
    "CollectionInput",
    "CollectionResult",
    "ExpectedProvenance",
    "RealityAdapterComponent",
    "RealityAdapterLock",
    "RealityArtifactRole",
    "RealityBundleVerificationResult",
    "RealityChainBinding",
    "RealityControlDelta",
    "RealityDeltaChange",
    "RealityEvidenceFact",
    "RealityEvidenceIndex",
    "RealityEvidenceItem",
    "RealityEvidenceManifestV2",
    "RealityManifestEntry",
    "RealityScopeArtifact",
    "RealityTargetLock",
    "RealityTraceArtifact",
    "RealityTraceArtifactV2",
    "RealityTraceEvent",
    "RealityTraceEventKind",
    "RealityTraceEventType",
    "RealityTraceEventV2",
    "RealityTraceFact",
    "RealityTraceLane",
    "VerificationResult",
    "collect_acceptance_evidence",
    "collect_from_json_file",
    "derive_reality_trace_v2",
    "semantic_sha256",
    "verify_acceptance_evidence",
    "verify_reality_pre_receipt_bundle",
]
